export default function Lipsum({ long }) {
  return <>
    {long ? <>
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam eu faucibus sapien. Donec lacinia enim cursus orci lobortis dapibus. In dictum metus ac nulla convallis sollicitudin. Sed sapien nibh, rhoncus imperdiet aliquet scelerisque, scelerisque rutrum justo. Phasellus mattis in metus et dignissim. Morbi semper consectetur arcu facilisis fermentum. Donec fringilla nunc eu fermentum euismod. Duis quis cursus lectus, at bibendum turpis. Cras mollis efficitur arcu id convallis.</p>
      <p>Integer vitae rhoncus lacus, vel blandit turpis. Donec eget massa eget metus tincidunt consequat. Praesent leo enim, fringilla quis efficitur nec, cursus non tortor. Maecenas non augue fringilla, volutpat massa sit amet, lobortis mi. In tristique tincidunt mi sed dictum. Suspendisse nulla justo, ornare fringilla lectus at, tincidunt scelerisque dui. Nam aliquet ante enim, nec dignissim nisi cursus ut. Phasellus fringilla eros vitae diam auctor, id imperdiet nunc fermentum. Duis nec finibus odio. Pellentesque feugiat finibus dui, nec porta mi aliquam sed. Aliquam vehicula tincidunt mollis. Maecenas lorem augue, tristique eu nibh ut, convallis scelerisque magna. Fusce rutrum eros at sapien fringilla convallis. Nam interdum lorem nec neque dignissim, ultrices facilisis nunc pellentesque. Phasellus convallis dui odio, at mattis dolor pretium at.</p>
      <p>Aliquam mollis tortor pharetra condimentum porttitor. Donec consequat eros urna, sed accumsan orci egestas ut. Ut a fringilla dui. Aliquam quis dui sodales, tempus lectus a, accumsan urna. Etiam lobortis tristique tortor, non scelerisque dolor finibus nec. Pellentesque vel turpis ultricies, pulvinar ante eu, rutrum nulla. Quisque aliquam ex justo, non rutrum neque egestas in. Maecenas tincidunt, magna sed viverra suscipit, velit nisi aliquam felis, eu convallis elit est a nisi. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam sodales eros eu mi scelerisque, in molestie leo vestibulum. Pellentesque et felis nibh.</p>
    </> : <></>}
    <p>Integer maximus tincidunt sapien, eget varius nisl finibus sed. Cras id felis ultricies, pharetra dui sed, dapibus diam. Donec tempor ante ut tellus scelerisque, vel vestibulum massa volutpat. Nullam at turpis mauris. Duis ullamcorper at dolor ac pharetra. Phasellus mattis semper quam, eget tempor mi dapibus id. Aliquam tincidunt, sapien a imperdiet mollis, turpis orci fermentum leo, sed sagittis magna lacus non nunc. Suspendisse sit amet dapibus lacus, vel fringilla sem. Aliquam venenatis mauris orci, ut sodales sem tincidunt eu. Cras in turpis et tellus tristique ullamcorper quis eu eros. Quisque et lacus a massa laoreet aliquam sit amet a elit. Quisque feugiat est vitae lacus pharetra faucibus. Ut commodo diam at scelerisque auctor.</p>
    <p>Sed cursus urna sed neque tincidunt bibendum ac dignissim arcu. Vivamus cursus, turpis eget cursus congue, lectus sem pretium nibh, vitae rutrum dui nisi vel erat. In hac habitasse platea dictumst. Maecenas sollicitudin leo ac commodo porta. Donec nisl ante, venenatis ut bibendum a, tincidunt nec sapien. Aenean sit amet massa varius, tempor nulla ut, pretium ipsum. Duis id justo elit. Nunc a est posuere, feugiat libero nec, malesuada metus. Nulla tincidunt, ex sed gravida pellentesque, quam eros tristique velit, ac dignissim felis urna ac lectus. </p>
  </>;
}
